config/routes.rb
Rails.application.routes.draw do
  resources :sectors
    # RESOURCES
    resources :portfolios
    resources :stocks 
    resources :portfolio_stocks
    # GET ROUTES
    get '/' => 'session#home'
  	get 'logged_out' => "session#logged_out"
    get '/login' => 'session#login' 
    get 'users/new'
    get 'users/create'
    get 'logout' => "session#logout"
    get 'stock/stock_quote' => 'stocks#stock_quote'
    get '/portfolios/:portfolio_id/add_stock' => 'portfolio_stocks#add_stock'
    get "portfolio_stocks" => "portfolio_stocks#index"


    # POST ROUTES
    post 'session/login_attempt' => 'session#login_attempt'
    post '/login' => 'session#login' 
    post 'users/create'

end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
	belongs_to :user
 	has_many :trades, dependent: :destroy
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]
  # GET /portfolios
  # GET /portfolios.json


  def index
    @portfolios = Portfolio.all
  end
  def stock_quote
    @stocks = Stock.all
    if @stocks.count > 0
    @string = ''
    @stocks.each do |element|
      @string = @string + element[:ticker] + ','
    end
  end
    @quote = StockQuote::Stock.quote(@string)
    return @quote
  end
  # GET /portfolios/1
  # GET /portfolios/1.json
  def show 
    @username = User.find(@portfolio.user)
    @join = PortfolioStock.all
    @quote = stock_quote
    return self
  end

  # GET /portfolios/new
  def new
    @portfolio = Portfolio.new
    @user = session[:user]

  end

  # GET /portfolios/1/edit
  def edit
    @stock = Stock.new
  end
 # def self.stocks
  #  @stocks = Stocks.select_all('ticker')
  #end
  # POST /portfolios
  # POST /portfolios.json
  def create
    @portfolio = Portfolio.new(portfolio_params)
    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully created.' }
        format.json { render :show, status: :created, location: @portfolio }
      else
        format.html { render :new }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portfolios/1
  # PATCH/PUT /portfolios/1.json
  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully updated.' }
        format.json { render :show, status: :ok, location: @portfolio }
      else
        format.html { render :edit }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolios/1
  # DELETE /portfolios/1.json
  def destroy
    @portfolio.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
 def portfolio_params
      params.require(:portfolio).permit(:user_id, :name)
    end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio
      @portfolio = Portfolio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
   
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
	def get_quotes
    	@string = ''
    	if @trades.count > 1
	    	@trades.each do |element|
	      		@string = @string + element[:ticker] + ','
	      	end
	    else
	    	@string = @trades[0][:ticker]
	    end
      	@quote = StockQuote::Stock::quote([@string], nil, nil, ['Symbol', 'Ask', 'Bid', 'LastTradePriceOnly'])
      	return @quote
	end
	def test(stuff)
		@things = stuff + ' things'
		return @things
	end
end

app/views/portfolios/_form.html.erb
<%= form_for(portfolio) do |f| %>
  <% if portfolio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(portfolio.errors.count, "error") %> prohibited this portfolio from being saved:</h2>

      <ul>
      <% portfolio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :user_id, value: @user[0]['user_id']%>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/portfolios/_table.html.erb
<strong>Stocks</strong>
<table class='stock-table'>
  <colgroup>
  <col style="width:80px">
  <col style="width:80px">
  <col style="width:80px">
  <col style="width:80px">
  <col style="width:80px">
  <col style="width:80px">
  <col style="width:80px">
  <col style="width:80px">
  <col style="width:80px">
  </colgroup>
  <tbody>
  	<tr>
  		<th>Ticker</th>
  		<th>Orig Price</th>
      <th>Last Trade</th>
  		<th>Quantity</th>
  		<th>Initial Cost</th>
  	</tr>
<% if @trades.count > 1 %>
<% @trades.zip(@prices) %>
<% @trades.zip(@prices).each do |trade, quote|%>
<% @convert =quote.change.to_f %>
<% @change_class = @convert >= 0 ? "positive" : "negative" %>
    <tr>
      <td><%=quote.symbol%></td>
      <td><%=trade[:price]%></td>
      <td><%=quote.last_trade_price_only%></td>
      <td><%=trade[:quantity]%></td>
      <td><%= trade[:quantity] * trade[:price]%></td>
    </tr>
<% end %>
<% else %>
    <tr>
      <td><%= @trades[0][:ticker] %></td>
      <td><%= @trades[0][:price] %></td>
      <td><%= @prices.last_trade_price_only %></td>
      <td><%= @trades[0][:quantity] %></td>
      <td><%= @trades[0][:quantity] * @trades[0][:price] %></td>
<% end %>

  </tbody>
</table>

app/views/portfolios/add_stock.html.erb
<h1> ADD STOCK FORM</h1>
<%= render 'portfolio_stocks/form' %> 

app/views/portfolios/edit.html.erb
<h1>Editing Portfolio</h1>

<%= render 'stocks/form', portfolio: @portfolio %> 

app/views/portfolios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Portfolios</h1>

<table>
  <thead> 
    <tr>
      <th>User</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @portfolios.each do |portfolio| %>
      <tr>
        <td><%= portfolio.user_id %></td>
        <td><%= portfolio.name %></td>
        <td><%= link_to 'Show', portfolio %></td>
        <td><%= link_to 'Edit', edit_portfolio_path(portfolio) %></td>
        <td><%= link_to 'Destroy', portfolio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Portfolio', new_portfolio_path %>

app/views/portfolios/new.html.erb
<h1>New Portfolio</h1>



<%= render 'form', portfolio: @portfolio %>

<%= link_to 'Back', portfolios_path %>

app/views/portfolios/show.html.erb
<div class='container'>
<p id="notice"><%= notice %></p>
<table>
<thead>
<col width="30%">
<col width="30%">
<col width="30%">
<th>Ticker</th>
<th>Sector</th>
<th>Price</th>
</thead>
<tbody>
<%= @join.inspect %>
</tbody>


<br>
 
 
<%= link_to 'Add Stock ', "#{@portfolio.id}/add_stock" %>|

</div>
 