config/routes.rb
Rails.application.routes.draw do
  resources :sectors
    # RESOURCES
    resources :portfolios
    resources :stocks 
    resources :portfolio_stocks
    # GET ROUTES
    get '/' => 'session#home'
  	get 'logged_out' => "session#logged_out"
    get '/login' => 'session#login' 
    get 'users/new'
    get 'users/create'
    get 'logout' => "session#logout"
    get 'stock/stock_quote' => 'stocks#stock_quote'
    get '/portfolios/:portfolio_id/add_stock' => 'portfolio_stocks#add_stock'
    get "portfolio_stocks" => "portfolio_stocks#index"


    # POST ROUTES
    post 'session/login_attempt' => 'session#login_attempt'
    post '/login' => 'session#login' 
    post 'users/create'

end

app/models/portfolio_stock.rb
class PortfolioStock < ApplicationRecord
	has_and_belongs_to_many :stocks
	has_and_belongs_to_many :portfolios
end

app/controllers/portfolio_stocks_controller.rb
class PortfolioStocksController < ApplicationController
  before_action :set_portfolio_stock, only: [:show, :edit, :update, :destroy]

  # GET /portfolio_stocks
  # GET /portfolio_stocks.json
  def index
    @portfolio_stocks = PortfolioStock.all
  end

  # GET /portfolio_stocks/1
  # GET /portfolio_stocks/1.json
  def show
  end

  def add_stock
    @portfolio = Portfolio.find(params[:portfolio_id])
    @portfolio_stock = PortfolioStock.new
    @stocks_array = Stock.all
    render 'add_stock'
  end
  # GET /portfolio_stocks/new
  def new
    @portfolio = Portfolio.find(params[:portfolio_id])
    @portfolio_stock = PortfolioStock.new

  end

  # GET /portfolio_stocks/1/edit
  def edit
  end

  # POST /portfolio_stocks
  # POST /portfolio_stocks.json
  def create
    @portfolio_stock = PortfolioStock.new(portfolio_stock_params)

    respond_to do |format|
      if @portfolio_stock.save
        format.html { redirect_to @portfolio_stock, notice: 'Portfolio stock was successfully created.' }
        format.json { render :show, status: :created, location: @portfolio_stock }
      else
        format.html { render :new }
        format.json { render json: @portfolio_stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portfolio_stocks/1
  # PATCH/PUT /portfolio_stocks/1.json
  def update
    respond_to do |format|
      if @portfolio_stock.update(portfolio_stock_params)
        format.html { redirect_to @portfolio_stock, notice: 'Portfolio stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @portfolio_stock }
      else
        format.html { render :edit }
        format.json { render json: @portfolio_stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolio_stocks/1
  # DELETE /portfolio_stocks/1.json
  def destroy
    @portfolio_stock.destroy
    respond_to do |format|
      format.html { redirect_to portfolio_stocks_url, notice: 'Portfolio stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio_stock
      @portfolio_stock = PortfolioStock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portfolio_stock_params
      params.require(:portfolio_stock).permit(:stock,:portfolio, :price, :quantity, :buy, :sell, :user_comment)
    end
end

app/helpers/portfolio_stocks_helper.rb
module PortfolioStocksHelper
end

app/views/portfolio_stocks/_form.html.erb
<%= form_for(@portfolio_stock) do |f| %>
  <% if @portfolio_stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@portfolio_stock.errors.count, "error") %> prohibited this portfolio_stock from being saved:</h2>

      <ul>
      <% @portfolio_stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>

    <%= @portfolio.inspect %>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/portfolio_stocks/add_stock.html.erb
<%= form_for(@portfolio_stock) do |f| %>
  <% if @portfolio_stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@portfolio_stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% @portfolio_stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= f.hidden_field :portfolio_id, value: @portfolio.id %>
<div class='field'>
<%= f.label 'Stock to Add' %>
<%= f.select(:stock_id) do %>
<% @stocks_array = Stock.all.map { |el| [el.ticker, el.id] } %>
<%= options_for_select(@stocks_array) %>
  <% end %>
  </div>

<div class='field'>
	<%= f.label :price %>
	<%= f.text_field :price%>
</div>

<div class='field'>
	<%= f.label :quantity %>
	<%= f.number_field :quantity %>
</div>

<div class='field'>
	<%= f.label :user_comment %>
	<%= f.text_field :user_comment %>
</div>
    <div class="field">
    <%= f.label :buy %>
    <%= f.radio_button :buy , 'buy'  %>
    <%= f.label :sell %>
    <%= f.radio_button :sell, 'sell' %>
    </div>

<%= f.submit %>

  <% end %>

app/views/portfolio_stocks/edit.html.erb
<h1>Editing Portfolio Stock</h1>

<%= render 'form', portfolio_stock: @portfolio_stock %>

<%= link_to 'Show', @portfolio_stock %> |
<%= link_to 'Back', portfolio_stocks_path %>

app/views/portfolio_stocks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Portfolio Stocks</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @portfolio_stocks.each do |portfolio_stock| %>
      <tr>
        <td><%= link_to 'Show', portfolio_stock %></td>
        <td><%= link_to 'Edit', edit_portfolio_stock_path(portfolio_stock) %></td>
        <td><%= link_to 'Destroy', portfolio_stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Portfolio Stock', new_portfolio_stock_path %>

app/views/portfolio_stocks/new.html.erb
<h1>New Portfolio Stock</h1>

<%= render 'form', portfolio_stock: @portfolio_stock %>

<%= link_to 'Back', portfolio_stocks_path %>

app/views/portfolio_stocks/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_portfolio_stock_path(@portfolio_stock) %> |
<%= link_to 'Back', portfolio_stocks_path %>