config/routes.rb
Rails.application.routes.draw do
  resources :sectors
    # RESOURCES
    resources :portfolios
    resources :stocks 
    resources :portfolio_stocks
    # GET ROUTES
    get '/' => 'session#home'
  	get 'logged_out' => "session#logged_out"
    get '/login' => 'session#login' 
    get 'users/new'
    get 'users/create'
    get 'logout' => "session#logout"
    get 'stock/stock_quote' => 'stocks#stock_quote'
    get '/portfolios/:portfolio_id/add_stock' => 'portfolio_stocks#add_stock'
    get "portfolio_stocks" => "portfolio_stocks#index"


    # POST ROUTES
    post 'session/login_attempt' => 'session#login_attempt'
    post '/login' => 'session#login' 
    post 'users/create'

end

app/models/stock.rb
class Stock < ApplicationRecord
has_many :portfolio_stocks, dependent: :destroy
has_many :portfolios, through: :portfolio_stocks
belongs_to :sector
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]
  include ApplicationHelper

  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show

  end

  # GET /stocks/new
  def new
    @sectors = Sector.all
    @stock = Stock.new
    @portfolios = Portfolio.all
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.require(:stock).permit(:ticker, :sector_id)
    end
end

app/helpers/stocks_helper.rb
module StocksHelper
	def test
		return "test"
	end
end

app/views/stocks/_form.html.erb
<%= form_for(@stock) do |f| %>
  <% if @stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ticker %>
    <%= f.text_field :ticker %>
  </div>
<%= f.label 'Sector' %>
<%= f.select(:sector_id) do %>
<% sectors_array = Sector.all.map { |sector| [sector.name, sector.id] } %>
<%= options_for_select(sectors_array) %>
  <% end %>





  <div class="actions">
  <br>
    <%= f.submit %>
  </div>
<% end %>

app/views/stocks/_table.html.erb
<strong>Stocks</strong>
<table class='stock-table'>
  <colgroup>
  <col style="width:80px">
  <col style="width:80px">
  <col style="width:80px">
  <col style="width:80px">
  <col style="width:80px">
  <col style="width:80px">
  <col style="width:80px">
  <col style="width:80px">
  <col style="width:80px">
  </colgroup>
  <tbody>
  	<tr>
  		<th>Ticker</th>
  		<th>Orig Price</th>
      <th>Last Trade</th>
  		<th>Quantity</th>
      <th>Test Ticker</th>
  		<th>Initial Cost</th>
      <th>Change</th>
      <th>Sector</th>
  	</tr>
<% @portfolio.stocks.zip(@quote) %>
<% @portfolio.stocks.zip(@quote).each do |stock, quote|%>
<% @convert =quote.change.to_f %>
<% @change_class = @convert >= 0 ? "positive" : "negative" %>
    <tr>
      <td><%=quote.symbol%></td>
      <td><%=stock[:price]%></td>
      <td><%=quote.last_trade_price_only%></td>
      <td><%=stock[:quantity]%></td>
      <td><%=stock[:ticker]%></td>
      <td><%= stock[:quantity] * stock[:price]%></td>
      <td class="<%= @change_class %>"><%= quote.change %></td>
      <td><%= Sector.find(stock[:sector_id]).name %></td>
    </tr>
    <%= @quote.each do |element|
      element
    end

    %>
<% end %>

  </tbody>
</table>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stocks</h1>

<table>
  <thead>
    <tr>
      <th>Ticker</th>
      <th>Sector</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td><%= stock.ticker %></td>
        <td><%= stock.sector.name %></td>
        <td><%= link_to 'Show', stock %></td>
        <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
        <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path %>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form', portfolio: @portfolio %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ticker:</strong>
  <%= @stock.ticker %>
</p>

<p>
<strong>Sector</strong>
<%= @stock.sector.name %>
</p>

<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>